"""add_is_all_day_to_calendar

Revision ID: f69f57c5a252
Revises: 1e5ebccca887
Create Date: 2026-07-28 01:27:00.180246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69f57c5a252'
down_revision: Union[str, None] = '1e5ebccca887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('is_all_day', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'is_all_day')
    # ### end Alembic commands ###
