"""Split Location and Service

Revision ID: f8fce1063d31
Revises: f521b4b859fd
Create Date: 2026-07-28 03:08:32.604215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fce1063d31'
down_revision: Union[str, None] = 'f521b4b859fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('locations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('map_link', sa.String(length=500), nullable=True))
    op.add_column('locations', sa.Column('approval_status', sa.String(length=20), nullable=False))
    op.drop_column('locations', 'is_approved')
    op.drop_column('locations', 'floor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'approval_status')
    op.drop_column('locations', 'map_link')
    op.drop_column('locations', 'description')
    op.drop_table('services')
    # ### end Alembic commands ###
